javaoperatorsdk:
  client:
    username: user
    password: password
    masterUrl: https://master.url
    openshift: true

  controllers:
    testcontroller:
      retry:
        maxAttempts: 3
        initialInterval: 1000
        intervalMultiplier: 1.5
        maxInterval: 50000
        maxElapsedTime: 100000